### ISSUE TITLE
`⍳10` returns `55.0` and not `1 2 3 4 5 6 7 8 9 10`

### ISSUE THREAD

**Issue by ArcticSpaceFox** [melsman/aplcompile#2]
I am currently trying to write some tests for a code execution bot, and I took this from tryapl.org, but instead of returning the list of values it gives us basically the expression `+/⍳10`, so it adds the elements all together. I think this might be a bug, but feel free to tell me otherwise

**Comment by melsman** [comment]
I guess you can think of it as a bug. It's assumed that the result is a scalar value - otherwise the compiler will add up the elements of the result array. You may want to take a look at github.com/melsman/apltail instead, which is a much more mature approach to compiling APL...
